{extend name="apps/common/view/admin.tpl" /}
<!-- -->
{block name="header_meta"}
<title>{:lang("upload_config")}－{:lang('appName')}</title>
{/block}
<!-- -->
{block name="main"}
<h6 class="border-bottom pb-2 text-purple">
	{:lang("upload_config")}
</h6>
{:DcBuildForm([
    'name'      => 'upload_index',
    'class'     => 'bg-white py-2 px-2',
    'action'    => DcUrl('admin/upload/update', 'module=common', ''),
    'method'    => 'post',
    'submit'    => lang('submit'),
    'reset'     => lang('reset'),
    'close'     => false,
    'disabled'  => false,
    'ajax'      => true,
    'callback'  => '',
    'items'     => [
        [
            'type'=>'text',
            'name'=>'upload_path',
            'id'=>'upload_path',
            'title'=>lang('upload_path'),
            'placeholder'=>lang('upload_path_placeholder'),
            'tips'=>'',
            'value'=>config('common.upload_path'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>true,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'',
            'class_tips'=>'',
        ],
        [
            'type'=>'text',
            'name'=>'upload_save_rule',
            'id'=>'upload_save_rule',
            'title'=>lang('upload_save_rule'),
            'placeholder'=>lang('upload_save_rule_placeholder'),
            'tips'=>'',
            'value'=>config('common.upload_save_rule'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'',
            'class_tips'=>'',
        ],
        [
            'type'=>'text',
            'name'=>'upload_max_size',
            'id'=>'upload_max_size',
            'title'=>lang('upload_max_size'),
            'placeholder'=>lang('upload_max_size_placeholder'),
            'tips'=>'',
            'value'=>config('common.upload_max_size'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'',
            'class_tips'=>'',
        ],
        [
            'type'=>'text',
            'name'=>'upload_file_ext',
            'id'=>'upload_file_ext',
            'title'=>lang('upload_file_ext'),
            'placeholder'=>lang('upload_file_ext_placeholder'),
            'tips'=>'',
            'value'=>config('common.upload_file_ext'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'',
            'class_tips'=>'',
        ],
        [
            'type'=>'text',
            'name'=>'upload_mime_type',
            'id'=>'upload_mime_type',
            'title'=>lang('upload_mime_type'),
            'placeholder'=>lang('upload_mime_type_placeholder'),
            'tips'=>'',
            'value'=>config('common.upload_mime_type'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'',
            'class_tips'=>'',
        ],
        [
            'type'=>'text',
            'name'=>'upload_referer',
            'id'=>'upload_referer',
            'title'=>lang('upload_referer'),
            'placeholder'=>lang('upload_referer_placeholder'),
            'tips'=>'',
            'value'=>config('common.upload_referer'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'',
            'class_tips'=>'',
        ],
        [
            'type'=>'text',
            'name'=>'upload_host',
            'id'=>'upload_host',
            'title'=>lang('upload_host'),
            'placeholder'=>lang('upload_host_placeholder'),
            'tips'=>'',
            'value'=>config('common.upload_host'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'',
            'class_tips'=>'',
        ],
        [
            'type'=>'text',
            'name'=>'upload_cdn',
            'id'=>'upload_cdn',
            'title'=>lang('upload_cdn'),
            'placeholder'=>lang('upload_cdn_placeholder'),
            'tips'=>'',
            'value'=>config('common.upload_cdn'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'',
            'class_tips'=>'',
        ],
    ]
])}
{/block}
<!-- -->
{block name="js"}
{/block}