<div class="modal-content">
    <div class="modal-body"> 
    {:DcBuildForm([
        'class'    => 'bg-white px-2 py-2 form-create',
        'action'   => DcUrl('admin/hook/save', '', ''),
        'method'   => 'post',
        'ajax'     => true,
        'submit'   => lang('submit'),
        'reset'    => lang('reset'),
        'close'    => lang('close'),
        'disabled' => false,
        'callback' => '',
        'data'     => '',
        'items'=>[
            [
                'type'=>'text',
                'name'=>'hook_name',
                'id'=>'hook_name',
                'title'=>lang('hook_name'),
                'placeholder'=>lang('hook_name_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'hook_path',
                'id'=>'hook_path',
                'title'=>lang('hook_path'),
                'placeholder'=>lang('hook_path_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'select',
                'name'=>'hook_overlay',
                'id'=>'hook_overlay',
                'title'=>lang('hook_overlay'),
                'placeholder'=>lang('hook_overlay_placeholder'),
                'tips'=>'',
                'value'=>'',
                'option'=>['no'=>lang('no'),'yes'=>lang('yes')],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'select',
                'name'=>'op_status',
                'id'=>'op_status',
                'title'=>lang('status'),
                'placeholder'=>lang('status_placeholder'),
                'tips'=>'',
                'value'=>'normal',
                'option'=>['normal'=>lang('normal'),'hidden'=>lang('hidden')],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'multiple'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'textarea',
                'name'=>'hook_info',
                'id'=>'hook_info',
                'title'=>lang('hook_info'),
                'placeholder'=>lang('hook_info_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'rows'=>3,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
        ]
    ])}
    </div>
</div>
