<div class="modal-content">
    <div class="modal-body"> 
    {:DcBuildForm([
        'name'     => 'hook_edit',
        'class'    => 'bg-white px-2 py-2 form-edit',
        'action'   => DcUrl('admin/hook/update', '', ''),
        'method'   => 'post',
        'submit'   => lang('submit'),
        'reset'    => lang('reset'),
        'close'    => lang('close'),
        'disabled' => false,
        'ajax'     => true,
        'callback' => '',
        'data'     => $data,
        'items'    => [
            [
                'type'=>'hidden',
                'name'=>'op_id',
                'value'=>$data['op_id'],
            ],
            [
                'type'=>'text',
                'name'=>'hook_name',
                'id'=>'hook_name',
                'title'=>lang('hook_name'),
                'placeholder'=>lang('hook_name_placeholder'),
                'tips'=>'',
                'value'=>$data['hook_name'],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'hook_path',
                'id'=>'hook_path',
                'title'=>lang('hook_path'),
                'placeholder'=>lang('hook_path_placeholder'),
                'tips'=>'',
                'value'=>$data['hook_path'],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'select',
                'name'=>'hook_overlay',
                'id'=>'hook_overlay',
                'title'=>lang('hook_overlay'),
                'placeholder'=>lang('hook_overlay_placeholder'),
                'tips'=>'',
                'value'=>$data['hook_overlay'],
                'option'=>['no'=>lang('no'),'yes'=>lang('yes')],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'select',
                'name'=>'op_status',
                'id'=>'op_status',
                'title'=>lang('status'),
                'placeholder'=>lang('status_placeholder'),
                'tips'=>'',
                'value'=>$data['op_status'],
                'option'=>['normal'=>lang('normal'),'hidden'=>lang('hidden')],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'multiple'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'textarea',
                'name'=>'hook_info',
                'id'=>'hook_info',
                'title'=>lang('hook_info'),
                'placeholder'=>lang('hook_info_placeholder'),
                'tips'=>'',
                'value'=>$data['hook_info'],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'rows'=>3,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
        ]
    ])}
    </div>
</div>
