<?php
//全局语言包
return [
    'indexAdmin'                    => '首页设置',	
    'site_title'                    => '首页标题',
    'site_title_placeholder'        => '自定义网站首页标题',	
    'site_keywords'                 => '首页关键字',
    'site_keywords_placeholder'     => '自定义网站首页关键字',
    'site_description'              => '首页描述',
    'site_description_placeholder'  => '自定义网站首页描述',
    'image_url'                     => '图床地址',
    'image_url_placeholder'         => '使用图床地址来提升图片的访问速度，不填写则不使用此功能',
    'api_bind'                      => '点击这里同步指定资源站的分类',
    'api_url'                       => '主资源站API接口',
    'api_url_placeholder'           => '主资源站API地址，可单独增加某个资源站的某一个分类',
    'api_params'                    => '主资源站附加参数',
    'api_params_placeholder'        => '主资源站附加参数将在请求资源站时拼装在一起，如a=1&b=2',
    'term_api_url'                  => '资源站API接口',
    'term_api_url_placeholder'      => '资源站API地址，可单独增加某个资源站的某一个分类',
    'term_api_params'               => '资源站附加参数',
    'term_api_params_placeholder'   => '资源站附加参数将在请求资源站时拼装在一起，如a=1&b=2',
    'term_api_tid'                  => '资源站分类ID',
    'term_api_tid_placeholder'      => '绑定资源站指定的分类ID，请通过资源站查询',
    'play0'                         => '播放地址1',
    'play1'                         => '播放地址2',
    'play2'                         => '播放地址3',
    'play3'                         => '播放地址4',
    'play4'                         => '播放地址5',
];