<div class="modal-content">
    <div class="modal-body"> 
    {:DcBuildForm([
        'name'     => 'nav_create',
        'class'    => 'bg-white px-2 py-2 form-create',
        'action'   => DcUrl('admin/nav/save', '', ''),
        'method'   => 'post',
        'submit'   => lang('submit'),
        'reset'    => lang('reset'),
        'close'    => lang('close'),
        'disabled' => false,
        'ajax'     => true,
        'callback' => '',
        'data'     => '',
        'items'    => [
            [
                'type'=>'text',
                'name'=>'nav_text',
                'id'=>'nav_text',
                'title'=>lang('name'),
                'placeholder'=>lang('name_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'select',
                'name'=>'nav_parent',
                'id'=>'nav_parent',
                'title'=>lang('parent'),
                'placeholder'=>lang('parent_placeholder'),
                'tips'=>'',
                'value'=>0,
                'option'=>DcNavOption(),
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'multiple'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'select',
                'name'=>'nav_target',
                'id'=>'nav_target',
                'title'=>lang('target'),
                'placeholder'=>lang('target_placeholder'),
                'tips'=>'',
                'value'=>'_blank',
                'option'=>['_blank'=>lang('target_option_0'),'_self'=>lang('target_option_1'),'_parent'=>lang('target_option_2'),'_top'=>lang('target_option_3'),'_new'=>lang('target_option_4')],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'multiple'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'select',
                'name'=>'nav_type',
                'id'=>'nav_type',
                'title'=>lang('nav_type'),
                'placeholder'=>lang('nav_type_placeholder'),
                'tips'=>'',
                'value'=>'link',
                'option'=>['link'=>lang('nav_type_option_0'),'addon'=>lang('nav_type_option_1')],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'multiple'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'nav_url',
                'id'=>'nav_url',
                'title'=>lang('url'),
                'placeholder'=>lang('url_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'nav_module',
                'id'=>'nav_module',
                'title'=>lang('nav_module'),
                'placeholder'=>lang('nav_module_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'nav_controll',
                'id'=>'nav_controll',
                'title'=>lang('nav_controll'),
                'placeholder'=>lang('nav_controll_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'nav_action',
                'id'=>'nav_action',
                'title'=>lang('nav_action'),
                'placeholder'=>lang('nav_action_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'nav_params',
                'id'=>'nav_params',
                'title'=>lang('params'),
                'placeholder'=>lang('params_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'nav_suffix',
                'id'=>'nav_suffix',
                'title'=>lang('suffix'),
                'placeholder'=>lang('suffix_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'nav_ico',
                'id'=>'nav_ico',
                'title'=>lang('ico'),
                'placeholder'=>lang('ico_placeholder'),
                'tips'=>'',
                'value'=>'fa fa-fw fa-list',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'nav_active',
                'id'=>'nav_active',
                'title'=>lang('active'),
                'placeholder'=>lang('active_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'op_module',
                'id'=>'op_module',
                'title'=>lang('module'),
                'placeholder'=>lang('module_placeholder'),
                'tips'=>'',
                'value'=>DcHtml($query['op_module']),
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'op_controll',
                'id'=>'op_controll',
                'title'=>lang('controll'),
                'placeholder'=>lang('controll_placeholder'),
                'tips'=>'',
                'value'=>DcHtml($query['op_controll']),
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'op_action',
                'id'=>'op_action',
                'title'=>lang('action'),
                'placeholder'=>lang('action_placeholder'),
                'tips'=>'',
                'value'=>DcHtml($query['op_action']),
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'number',
                'name'=>'op_order',
                'id'=>'op_order',
                'title'=>lang('weight'),
                'placeholder'=>lang('weight_placeholder'),
                'tips'=>'',
                'value'=>0,
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
        ]
    ])}
    </div>
</div>
