<div class="modal-content">
    <div class="modal-body">
    {:DcBuildForm([
        'class'    => 'bg-white px-2 py-2 form-create',
        'action'   => DcUrl('admin/route/save', '', ''),
        'method'   => 'post',
        'ajax'     => true,
        'submit'   => lang('submit'),
        'reset'    => lang('reset'),
        'close'    => lang('close'),
        'disabled' => false,
        'callback' => '',
        'data'     => '',
        'items'=>[
            [
                'type'=>'hidden',
                'name'=>'op_module',
                'value'=>$op_module,
            ],
            [
                'type'=>'text',
                'name'=>'rule',
                'id'=>'rule',
                'title'=>lang('route_rule'),
                'placeholder'=>lang('route_rule_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'address',
                'id'=>'address',
                'title'=>lang('route_address'),
                'placeholder'=>lang('route_address_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'select',
                'name'=>'method',
                'id'=>'method',
                'title'=>lang('route_method'),
                'placeholder'=>lang('route_method_placeholder'),
                'tips'=>'',
                'value'=>'get',
                'option'=>['get'=>lang('route_method_option_0'),'post'=>lang('route_method_option_1'),'put'=>lang('route_method_option_2'),'delete'=>lang('route_method_option_3'),'*'=>lang('route_method_option_4')],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'multiple'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'select',
                'name'=>'op_status',
                'id'=>'op_status',
                'title'=>lang('status'),
                'placeholder'=>lang('status_placeholder'),
                'tips'=>'',
                'value'=>'normal',
                'option'=>['normal'=>lang('normal'),'hidden'=>lang('hidden')],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'multiple'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'json',
                'name'=>'option',
                'id'=>'option',
                'title'=>lang('route_option'),
                'placeholder'=>lang('route_option_placeholder'),
                'tips'=>'',
                'value'=>'',
                'rows'=>6,
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'json',
                'name'=>'pattern',
                'id'=>'pattern',
                'title'=>lang('route_pattern'),
                'placeholder'=>lang('route_pattern_placeholder'),
                'tips'=>'',
                'value'=>'',
                'rows'=>6,
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
        ]
    ])}
    </div>
</div>