<div class="modal-content">
    <div class="modal-body"> 
    {:DcBuildForm([
        'name'     => 'user_create',
        'class'    => 'bg-white px-2 py-2 form-create',
        'action'   => DcUrl('admin/user/save', '', ''),
        'method'   => 'post',
        'submit'   => lang('submit'),
        'reset'    => lang('reset'),
        'close'    => lang('close'),
        'disabled' => false,
        'ajax'     => true,
        'callback' => '',
        'data'     => '',
        'items'    => [
            [
                'type'=>'text',
                'name'=>'user_name',
                'id'=>'user_name',
                'title'=>lang('user_name'),
                'placeholder'=>lang('user_name_placeholder'),
                'tips'=>lang('user_name_tips'),
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'autocomplete'=>'off',
                'maxlength'=>'40',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'col-12 pt-1 text-muted small',
            ],
            [
                'type'=>'password',
                'name'=>'user_pass',
                'id'=>'user_pass',
                'title'=>lang('user_pass'),
                'placeholder'=>lang('user_pass_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'autocomplete'=>'on',
                'maxlength'=>'32',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'email',
                'name'=>'user_email',
                'id'=>'user_email',
                'title'=>lang('user_email'),
                'placeholder'=>lang('user_email_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'autocomplete'=>'off',
                'maxlength'=>'120',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'user_mobile',
                'id'=>'user_mobile',
                'title'=>lang('user_mobile'),
                'placeholder'=>lang('user_mobile_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'autocomplete'=>'off',
                'maxlength'=>'11',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'select',
                'name'=>'user_capabilities',
                'id'=>'user_capabilities',
                'title'=>lang('user_capabilities'),
                'placeholder'=>lang('user_capabilities_placeholder'),
                'tips'=>'',
                'value'=>'guest',
                'option'=>DcRolesOption(),
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'multiple'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ]
        ]
    ])}
    </div>
</div>
