{extend name="./apps/common/view/admin.tpl" /}
<!-- -->
{block name="header_meta"}
<title>{:lang("admin_poster")}－{:lang('appName')}</title>
{/block}
{block name="header_addon"}
<link href="{$path_root}{$path_addon}view/theme.css" rel="stylesheet">
<script src="{$path_root}{$path_addon}view/theme.js"></script>
{/block}
<!-- -->
{block name="main"}
<h6 class="border-bottom pb-2 text-purple">
  {:lang("admin_poster")}
</h6>
{:DcBuildForm([
    'class'    => 'bg-white px-2 py-2',
    'action'   => DcUrlAddon(['module'=>'maccms','controll'=>'admin','action'=>'update'],''),
    'method'   => 'post',
    'ajax'     => true,
    'submit'   => lang('submit'),
    'reset'    => lang('reset'),
    'close'    => false,
    'disabled' => false,
    'callback' => '',
    'items'   => [
        [
            'type'=>'textarea',
            'name'=>'header_pc',
            'id'=>'header_pc',
            'title'=>lang('header_pc'),
            'placeholder'=>lang('header_pc_placeholder'),
            'tips'=>'<p>调用代码</p><p>'.DcTplLabelOp('maccms','header_pc').'</p>',
            'value'=>config('maccms.header_pc'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'rows'=>4,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'form-control form-control-sm',
            'class_tips'=>'',
        ],
        [
            'type'=>'textarea',
            'name'=>'thread_pc',
            'id'=>'thread_pc',
            'title'=>lang('thread_pc'),
            'placeholder'=>lang('thread_pc_placeholder'),
            'tips'=>'<p>调用代码</p><p>'.DcTplLabelOp('maccms','thread_pc').'</p>',
            'value'=>config('maccms.thread_pc'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'rows'=>4,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'form-control form-control-sm',
            'class_tips'=>'',
        ],
        [
            'type'=>'textarea',
            'name'=>'footer_pc',
            'id'=>'footer_pc',
            'title'=>lang('footer_pc'),
            'placeholder'=>lang('footer_pc_placeholder'),
            'tips'=>'<p>调用代码</p><p>'.DcTplLabelOp('maccms','footer_pc').'</p>',
            'value'=>config('maccms.footer_pc'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'rows'=>4,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'form-control form-control-sm',
            'class_tips'=>'',
        ],
        [
            'type'=>'textarea',
            'name'=>'left_pc',
            'id'=>'left_pc',
            'title'=>lang('left_pc'),
            'placeholder'=>lang('left_pc_placeholder'),
            'tips'=>'<p>调用代码</p><p>'.DcTplLabelOp('maccms','left_pc').'</p>',
            'value'=>config('maccms.left_pc'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'rows'=>4,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'form-control form-control-sm',
            'class_tips'=>'',
        ],
        [
            'type'=>'textarea',
            'name'=>'center_pc',
            'id'=>'center_pc',
            'title'=>lang('center_pc'),
            'placeholder'=>lang('left_pc_placeholder'),
            'tips'=>'<p>调用代码</p><p>'.DcTplLabelOp('maccms','center_pc').'</p>',
            'value'=>config('maccms.center_pc'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'rows'=>4,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'form-control form-control-sm',
            'class_tips'=>'',
        ],
        [
            'type'=>'textarea',
            'name'=>'right_pc',
            'id'=>'right_pc',
            'title'=>lang('right_pc'),
            'placeholder'=>lang('left_pc_placeholder'),
            'tips'=>'<p>调用代码</p><p>'.DcTplLabelOp('maccms','right_pc').'</p>',
            'value'=>config('maccms.right_pc'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'rows'=>4,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'form-control form-control-sm',
            'class_tips'=>'',
        ],
        [
            'type'=>'textarea',
            'name'=>'one_pc',
            'id'=>'one_pc',
            'title'=>lang('one_pc'),
            'placeholder'=>lang('one_pc_placeholder'),
            'tips'=>'<p>调用代码</p><p>'.DcTplLabelOp('maccms','one_pc').'</p>',
            'value'=>config('maccms.one_pc'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'rows'=>4,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'form-control form-control-sm',
            'class_tips'=>'',
        ],
        [
            'type'=>'textarea',
            'name'=>'two_pc',
            'id'=>'two_pc',
            'title'=>lang('two_pc'),
            'placeholder'=>lang('two_pc_placeholder'),
            'tips'=>'<p>调用代码</p><p>'.DcTplLabelOp('maccms','two_pc').'</p>',
            'value'=>config('maccms.two_pc'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'rows'=>4,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'form-control form-control-sm',
            'class_tips'=>'',
        ],
        [
            'type'=>'textarea',
            'name'=>'three_pc',
            'id'=>'three_pc',
            'title'=>lang('three_pc'),
            'placeholder'=>lang('three_pc_placeholder'),
            'tips'=>'<p>调用代码</p><p>'.DcTplLabelOp('maccms','three_pc').'</p>',
            'value'=>config('maccms.three_pc'),
            'readonly'=>false,
            'disabled'=>false,
            'required'=>false,
            'rows'=>4,
            'class'=>'row form-group',
            'class_left'=>'col-md-2',
            'class_right'=>'col-md-6',
            'class_right_control'=>'form-control form-control-sm',
            'class_tips'=>'',
        ],
    ]
])}
{/block}
<!-- -->
{block name="js"}
{/block}