<div class="modal-content">
    <div class="modal-body"> 
    {:DcBuildForm([
        'class'    => 'bg-white px-2 py-2 form-create',
        'action'   => DcUrl('admin/category/save', '', ''),
        'method'   => 'post',
        'ajax'     => true,
        'submit'   => lang('submit'),
        'reset'    => lang('reset'),
        'close'    => lang('close'),
        'disabled' => false,
        'callback' => '',
        'data'     => '',
        'items'=>[
            [
                'type'=>'hidden',
                'name'=>'term_much_type',
                'value'=>'category',
            ],
            [
                'type'=>'text',
                'name'=>'term_name',
                'id'=>'term_name',
                'title'=>lang('name'),
                'placeholder'=>lang('name_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'autocomplete'=>'off',
                'maxlength'=>'30',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'term_slug',
                'id'=>'term_slug',
                'title'=>lang('slug'),
                'placeholder'=>lang('slug_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'autocomplete'=>'on',
                'maxlength'=>'60',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'select',
                'name'=>'term_much_parent',
                'id'=>'term_much_parent',
                'title'=>lang('parent'),
                'placeholder'=>lang('parent_placeholder'),
                'tips'=>'',
                'value'=>0,
                'option'=>DcCategoryOption(),
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'multiple'=>false,
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'term_module',
                'id'=>'term_module',
                'title'=>lang('module'),
                'placeholder'=>lang('module_placeholder'),
                'tips'=>'',
                'value'=>DcEmpty($query['op_module'],'common'),
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'autocomplete'=>'on',
                'maxlength'=>'60',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'term_much_info',
                'id'=>'term_much_info',
                'title'=>lang('info'),
                'placeholder'=>lang('info_placeholder'),
                'tips'=>'',
                'value'=>'',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'autocomplete'=>'on',
                'maxlength'=>'11',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'number',
                'name'=>'term_order',
                'id'=>'term_order',
                'title'=>lang('weight'),
                'placeholder'=>lang('weight_placeholder'),
                'tips'=>'',
                'value'=>0,
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'autocomplete'=>'off',
                'maxlength'=>'5',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'term_tpl',
                'id'=>'term_tpl',
                'title'=>lang('tpl'),
                'placeholder'=>lang('tpl_placeholder'),
                'tips'=>'',
                'value'=>'index',
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'autocomplete'=>'on',
                'maxlength'=>'100',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_right_tips'=>'',
            ],
        ]
    ])}
    </div>
</div>
