<div class="modal-content">
    <div class="modal-body">
    {:DcBuildForm([
        'name'     => 'tag_edit',
        'class'    => 'bg-white px-2 py-2 form-edit',
        'action'   => DcUrl('admin/tag/update', '', ''),
        'method'   => 'post',
        'submit'   => lang('submit'),
        'reset'    => lang('reset'),
        'close'    => lang('close'),
        'disabled' => false,
        'ajax'     => true,
        'callback' => '',
        'data'     => $data,
        'items'    => [
            [
                'type'=>'hidden',
                'name'=>'term_id',
                'value'=>$data['term_id'],
            ],
            [
                'type'=>'text',
                'name'=>'term_name',
                'id'=>'term_name',
                'title'=>lang('name'),
                'placeholder'=>lang('tag_name_placeholder'),
                'tips'=>'',
                'value'=>$data['term_name'],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'autocomplete'=>'on',
                'maxlength'=>'30',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'term_slug',
                'id'=>'term_slug',
                'title'=>lang('slug'),
                'placeholder'=>lang('slug_placeholder'),
                'tips'=>'',
                'value'=>$data['term_slug'],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'autocomplete'=>'on',
                'maxlength'=>'60',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'term_module',
                'id'=>'term_module',
                'title'=>lang('module'),
                'placeholder'=>lang('module_placeholder'),
                'tips'=>'',
                'value'=>DcEmpty($data['term_module'],'common'),
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'autocomplete'=>'on',
                'maxlength'=>'60',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'term_much_info',
                'id'=>'term_much_info',
                'title'=>lang('info'),
                'placeholder'=>lang('info_placeholder'),
                'tips'=>'',
                'value'=>$data['term_much_info'],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>false,
                'autocomplete'=>'on',
                'maxlength'=>'100',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'number',
                'name'=>'term_order',
                'id'=>'term_order',
                'title'=>lang('weight'),
                'placeholder'=>lang('weight_placeholder'),
                'tips'=>'',
                'value'=>$data['term_order'],
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'autocomplete'=>'off',
                'maxlength'=>'5',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
            [
                'type'=>'text',
                'name'=>'term_tpl',
                'id'=>'term_tpl',
                'title'=>lang('tpl'),
                'placeholder'=>lang('tpl_placeholder'),
                'tips'=>'',
                'value'=>DcEmpty($data['term_tpl'],'index'),
                'readonly'=>false,
                'disabled'=>false,
                'required'=>true,
                'autocomplete'=>'on',
                'maxlength'=>'30',
                'class'=>'row form-group',
                'class_left'=>'col-12',
                'class_right'=>'col-12',
                'class_right_control'=>'',
                'class_tips'=>'',
            ],
        ]
    ])}
    </div>
</div>